### ISSUE TITLE
Pruning takes to much

### ISSUE THREAD

**Issue by huskelord** [lurkbbs/e621dl#18]
[configs.zip](https://github.com/lurkbbs/e621dl/files/3992839/configs.zip)

don't know why but whenever it have it set to prune my cache and donwloads it wipes out everyting and i don't know why

Haven't tested it much but pruning doesn't seem to work all that much.

**Comment by lurkbbs** [comment]
I'm on it

**Comment by huskelord** [comment]
i figured it out i think. i'm testing it now but i belive it got rid of everyting except whatever was posted over the last 10 days because i limited days value to 10 to save time. running it now to see if it works right after changing the days value back to 999999

**Comment by lurkbbs** [comment]
IDK, everything works fine and just as it specified.
Just now, I downloaded e621dl.exe, all configs, first run it to get images, then I changed second config to prune everything and ran it again.

First, only last 10 days are actually requested and loaded to database. Second, third config is with disabled cache, so it maybe not pruning but just not filling cache. 

Now, let's take a look. Suppose we downloaded....

Doesn't matter, you're figured it out 😄

**Comment by lurkbbs** [comment]
By the way, if you want to update database only for the last few days, you can make a copy of relevant config, change it to db and set max_days_ago to a big number. 999999 is about 2700 years back, should be good enough. But, I sometimes get tag update for posts of 7 years or more, so I prefer to get it all anyway.
Next thing, I recommend to get all api only in the first config, since you most permissive prefilter is the same across configs and getting everything from api second time is somewhat meaningless and rather slow

**Comment by huskelord** [comment]
The reason I have artists on their own is because i want download pools to only be for artists and not anyting else when you get around to it. I guess I can just add it to a separate db config now that I think about it
Edit1: I actually cant because the first api is s q and e posts while the second is only e

**Comment by huskelord** [comment]
Just curious but is there a way that I could get posts that I'll bypass the default blacklisting because I'm sure there will be a few in some comics that i will want once the pool gets done

**Comment by huskelord** [comment]
im having trouble with my currrent config settup it keep skiping the first config even though i know that there are some post that need to be downloaded/copied that aren't

[configs.zip](https://github.com/lurkbbs/e621dl/files/3994518/configs.zip)

edit1: I think i fixed it by changing the config names from config1 to 1 config
edit2: nvm I'm running to a bunch of other problems too.  i updated the config.zip to what i curenlty have but im going to run on no_close and try to figure this out.
Edit3: it was the date again. but i think i noticed a problem related to that the program will run only as long as the shortes or first date value nomater what config it is on, If the first/shortest date value is 15 all configs will only run the date value at 15 (I could be wrong but it doesn't change the fact that the configs wouldn't run to completion

**Comment by lurkbbs** [comment]
> If the first/shortest date value is 15 all configs will only run the date value at 15

If you deleted `posts.db` then in new database there is no posts beyond 30 days therefore all posts from db ends earlier then expected.
Check `posts.db` size. If it's more than 1 GB, it is really a bug. If it's smaller, most likely less than 100 Mb, than it's not a bug and you need to get all posts from api at least once.

>Just curious but is there a way that I could get posts that I'll bypass the default blacklisting because I'm sure there will be a few in some comics that i will want once the pool gets done

Not for now. By the time pools are actually relevant global blacklist mechanics as well as all the settings will be changed anyway

**Comment by huskelord** [comment]
Merry christamas (its the day after but so what.) ive been away for the holidays and didn't get a chance to get back with you until now. 

for the bug above i forgot the check the file itself but when i downloaded with the date value at 10 until completion only a few files survived the pruning but when i changed it back everyting was fine. 

After i did a mass self blacklisting and reran the program to completion i noticed that the to_blacklist_post folder was empty like its supposed to be but the the post were back in the folders i grabed them from to blacklist them. the blacklist document also didn't have the post names in it.

here are the configs i got
[configs.zip](https://github.com/lurkbbs/e621dl/files/4004004/configs.zip)

**Comment by lurkbbs** [comment]
Merry Christmas!
By the way, we, Russians, we still use Julian calendar in our Orthodox church, so it's about 13 day before. But who cares, that means we have two Christmas symmetrically before and after New Year! So merry import Christmas, wait for export Christmas on 7 of January 😄 

For the bugs, I'll look into it tomorrow. As I understand it, posts from "blacklist.txt" are there in the folders despite being in the blacklist. Not good, I'll make it disappear tomorrow or in the Sunday.

From 30 of December to 3 of January I'll be unavailable, because we Atheistic Russians celebrate New Year as a great holiday, not Christmas, which is a nice bonus. And by celebrate I mean be drunk (one day) and relax (another day) and play games I wanted to play a looong time ago (another day).

Well, not many are actually atheist these days, but New Year is really about the same thing as Christmas in at least USA, Canada and Western Europe, but most likely everywhere else. Eight days of no work (1-8 January) included. And that means I'll finally be able to _improve_ e621dl, not just minor patches and bugfixes here and there.

**Comment by huskelord** [comment]
Sounds great hope to hear from you soon.

**Comment by lurkbbs** [comment]
I couldn't reproduce the bug.

Changes from configs:
* Disabled cache pruning
* Added `make_cache = true` to the second config
* `offline = true` in all configs

My steps:

1. Run configs.
2. Copy `specifed for blacklisting` folder to `to_blocked_posts`
3. Run configs. At that point `specifed for blacklisting` was removed from downloads
4. Run configs again. Blacklisted posts was not copied.

I tried to add random files to downloads folder, as well as `to_blocked_posts` folder. Everything was fine.

There is one thing that could cause blacklist.txt to be cleared. If the app was terminated in exactly wrong moment when the file was updated, then it could be cleared but not updated.

If your problem is still there, after you copied/moved files to `to_blocked_posts`, run powershell from the folder and execute:
`tree /F /A > "files.txt"`
from there and upload files.txt here. Inside should be filenames and folder structure.

**Comment by huskelord** [comment]
sorry for the late reply everyting seems to be working when it comes to the blacklisting it must have been my timing closeing the config.

**Comment by lurkbbs** [comment]
Still not sure what happened there, but alright.

I as said, I want to change a lot, and I want to start with configuration format. Classic *.ini files are bad at hierarchical structures. So, I chose YAML, it will look like that:

```yaml
global settings:
    # include_md5 : false -- to hell with that
    # make_hardlinks : true -- always.
    #                  more than that, app should check if
    #                  it's possible, and if not, try
    #                  symlinks, and only then copies
    # make_cache : true -- also always true. We use
    #                      hardlinks! Or symlinks,
    #                      doesn't matter much. Copies
    #                      only if there is no possible way
    #                      to make either of the above
    # db : true  -- this is true too. Too much of
    #               advanced case scenarios just won't work
    #               and frankly, I'm tired of all the flags
    #               and how they should work with each other
    prune downloads : false
    prune cache : false
    offline : true
    # I plan to add a folder where
    # every new images are hardlinked
    # folder structure is similar
    # with downloads
    # should be cleared on every new run
    recent updates folder: new

anchors:
    gender interactions: &gi 
        - solo
        - another_tag
        - yet_another_tag
    everything and misc: &em
        misc subfolder : .Overflow
        everything subfolder: ...Everything
    blacklist: &bl
        - bad_tag
        - another_bad_tag

section settings templates:
    defaults:
        #days should not be 
        days : 999999
        ratings : s q e
        min score : 0
        min favs : 0
        # posts_from should not be on per folder basis
        # it's only valid for queries
        
        blacklist:
            - *bl
        
        everything subfolder: false
        misc subfolder : false
        
        subfolders :
            - ..images:
                << : *em
                tags:
                    - -animated
                subfolders:
                    - *gi
                
            
            - ..Animated:
                tags: animated
                subfolders: 
                    - sound:
                        << : *em
                        tags:
                            - sound
                        subfolders:
                            - *gi
                    - No_Sound:
                        << : *em
                        tag: 
                            - -sound
                        subfolders:
                            - *gi
            

    no subfolders:
        base: defaults
        subfolders : 

folders:
    species:
        subfolders:
            - Animal Base:
                subfolders:
                    - arthropod:
                        subfolders:
                            - hymenopteran:
                                tags:
                                    - hymenopteran
                                subfolders:
                                    - wasp
                                    - hornet
                                    - bee
                                    - ant
                                misc subfolder : .hymenopteran_-specified
                            - lepidopteran:
                                tags:
                                    - lepidopteran
                                subfolders:
                                    - butterfly
                                    - moth
                                misc subfolder : .lepidopteran_-specified
                            - arachnid
                            - myriapod:
                                tags:
                                    - myriapod
                                subfolders:
                                    - millipede
                                    - centipede
                                misc subfolder : .myriapod_-specified
                            - mantis
                    - Rodent:
                        subfolders:
                            - murid:
                                tags:
                                    - murid
                                subfolders:
                                    - mouse
                                    - rat
                                misc subfolder : .myriapod_-specified

queries:
    Everything_images:
        # Note: no additional time constraint
        query: -animated
        query source: remote # "local" for local database
        # Queries have all the properties of folders
        # but everything related with subfolders
        # and actual downloading of files is
        # ignored if this option is in use:
        used folders:
            - species
            
    Everything_animated:
        query:  animated
        query source: remote 
        used folders:
            - species
```

YAML do not requires quotes everywhere and generally easy to than TOML. Unlike ini-files, yaml supports hierarchical structures rather easy. Also, it has build-in support for [anchors, aliases and merges](http://blogs.perl.org/users/tinita/2019/05/reusing-data-with-yaml-anchors-aliases-and-merge-keys.html), similar to my hack with [*subfolders], but since it supports hierarchy, they should be less frequent.

There are two downsides:
    1. It is a bit more complex than classic ini file.
    2. It's hard to work with YAML in classic Notepad, especially when it gets bigger. I work with [Notepad++](https://notepad-plus-plus.org/), there is [Notepad2](http://www.flos-freeware.ch/notepad2.htm) and some more.

I'll give you test yaml config for all your three configs, in one file. Check it out:
[test.zip](https://github.com/lurkbbs/e621dl/files/4020101/test.zip)
